---
abstract: "get/post url, return unicode content, auto detect CJK charset\r"
author:
  - 'abbypan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Novel-Robot-Browser
requires:
  Encode::Detect::CJK: '0'
  HTTP::Tiny: '0'
  IO::Uncompress::Gunzip: '0'
  Parallel::ForkManager: '0'
  Term::ProgressBar: '0'
version: '0.16'
